[xdebug]
; Custom Xdebug configuration
; zend_extension is loaded by docker-php-ext-xdebug.ini

xdebug.mode=develop,debug,coverage
xdebug.start_with_request=yes
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
xdebug.idekey=PHPSTORM

; Logs
xdebug.log=/var/www/var/log/xdebug.log
xdebug.log_level=0

; Performance
xdebug.max_nesting_level=512
