security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User\Admin:
            algorithm: auto
            cost: 15

    providers:
        app_admin_provider:
            entity:
                class: App\Entity\User\Admin
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/io
            lazy: true
            provider: app_admin_provider
            user_checker: App\Security\AdminUserChecker
            form_login:
                login_path: backend_security_login
                check_path: backend_security_login
                default_target_path: backend_dashboard_index
                always_use_default_target_path: false
                enable_csrf: true
            logout:
                path: admin_security_logout
                target: admin_security_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                name: APP_REMEMBER
                token_provider:
                    doctrine: true
            switch_user: true

    access_control:
        - { path: ^/io/connexion, roles: PUBLIC_ACCESS }
        - { path: ^/io, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: [ ROLE_USER, ROLE_ALLOWED_TO_SWITCH ]

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
