name: Deploy Production

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  deploy-prod:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: production
      docker_compose_file: docker-compose.prod.yaml
      nginx_port: "8081"
      site_url: "https://www.florian-neveu.com"
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      USER_ID: ${{ secrets.USER_ID }}
      GROUP_ID: ${{ secrets.GROUP_ID }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH_PROD }}
      BACKUP_PATH: ${{ secrets.BACKUP_PATH }}
