name: Deploy Preprod

on:
  workflow_run:
    workflows: ["CI"]
    branches: [develop]
    types:
      - completed

jobs:
  deploy-preprod:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: preprod
      docker_compose_file: docker-compose.preprod.yaml
      nginx_port: "8082"
      site_url: "http://preprod.florian-neveu.com"
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      USER_ID: ${{ secrets.USER_ID }}
      GROUP_ID: ${{ secrets.GROUP_ID }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH_PREPROD }}
